---
language: node_js
node_js:
  - "6.10.3"

sudo: required

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

dist: trusty

addons:
  chrome: stable

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - npm config set spin false
  - npm install -g npm@^5
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install:
  - npm install -g bower
  - npm install
  - npm rebuild node-sass
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test

after_script:
  - test $EMBER_TRY_SCENARIO == "default" && test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop" || test $TRAVIS_BRANCH == "dummy-test")  && ember build --gh-pages --gh-pages-branch=$TRAVIS_BRANCH && bash scripts/deploy-to-gh-pages.sh
